[project]
name = "homeofficinator"
version = "1.1.0"
dependencies = [
    "pydantic",
    "PyQt6",
    "requests",
]
requires-python = ">=3.10"
authors = [
    { name = "Alexis Braine", email = "alexis.braine94@gmail.com" }
]
license = { text = "GPL v3" }